### ISSUE TITLE
Scelta della riproduzione

### ISSUE THREAD

**Issue by Stefanoz45** [Be4t5/Netfreex#1]
Ciao, complimenti per l'app. La ho installata sulla sony Bravia kdl e ho notato una cosa, per scegliere l'host dal dove riprodurre il film mi seleziona il quadrato nero con dentro i vari host ma non posso selezionare l'host così facendo se provo mi seleziona un altro episodio/film. Grazie in  anticipo

**Comment by Be4t5** [comment]
Ciao, la stai utilizzando con le frecce del telecomando? Al momento l'app è
ottimizzata per mouse e touch... Il telecomando non pienamente
Il 22 mag 2016 15:57, "Stefanoz45" <notifications@github.com> ha scritto:

**Comment by Stefanoz45** [comment]
si. Proverò con un mouse e ti farò sapere. Grazie mille

**Comment by Stefanoz45** [comment]
Mi sono appena accorto di non aver mai risposto. Con il mouse funziona a meraviglia. Ho scaricato l'ultima versione e mi trovo molto bene che ci sia pure la scelta di videomega
